name: CI/CD pipeline

on:
  push:
    branches:
      - main

jobs:
  container-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Google Container Registry
        run: echo $GCR_TOKEN | docker login -u _json_key --password-stdin https://gcr.io
        env:
          GCR_TOKEN: ${{ secrets.MA_GCLOUD_TOKEN }}

      - name: Build and Push Backend Docker image
        run: |
          docker build -t gcr.io/${{ secrets.MA_GCLOUD_PROJECT }}/majedamjadregistry:backend-latest backend/
          docker push gcr.io/${{ secrets.MA_GCLOUD_PROJECT }}/majedamjadregistry:backend-latest

      # - name: Build and Push Frontend Docker image
      #   run: |
      #     docker build -t gcr.io/${{ secrets.MA_GCLOUD_PROJECT }}/majedamjadregistry:frontend-latest frontend/
      #     docker push gcr.io/${{ secrets.MA_GCLOUD_PROJECT }}/majedamjadregistry:frontend-latest

      - name: Authenticate to Google Cloud
        run: echo '${{ secrets.MA_GCLOUD_TOKEN }}' > admin.json && gcloud auth activate-service-account --key-file=./admin.json
      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials majed-amjad-cluster --zone us-central1-a --project nifty-catfish-395105

      - name: Deploy Backend Cloud Run
        run: |
          gcloud run deploy backend --image gcr.io/${{ secrets.MA_GCLOUD_PROJECT }}/majedamjadregistry:backend-latest --platform managed --region us-central1 --allow-unauthenticated
          env:
            GCLOUD_RUN_AUTHENTICATION: ${{ secrets.MA_GCLOUD_TOKEN }}

      # - name: Deploy Frontend Cloud Run
      #   run: |
      #     gcloud run deploy frontend --image gcr.io/${{ secrets.MA_GCLOUD_PROJECT }}/majedamjadregistry:frontend-latest --platform managed --region us-central1 --allow-unauthenticated
      #     env:
      #       GCLOUD_RUN_AUTHENTICATION: ${{ secrets.MA_GCLOUD_TOKEN }}
