  name: CI/CD pipeline
  
  on:
    push:
      branches:
        - main
  
  jobs:
    container-deploy:
      runs-on: ubuntu-latest
  
      steps:
        - name: Check out code
          uses: actions/checkout@v2
  
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
  
        - name: Authenticate to Google Cloud
          run: gcloud auth activate-service-account --key-file=./admin.json
        
        - name: Configure kubectl
          run: |
            gcloud container clusters get-credentials majed-amjad-cluster --zone us-central1-a --project nifty-catfish-395105
            
        - name: Login to Artifact Registry
          run: cat ./admin.json | docker login -u _json_key --password-stdin https://northamerica-northeast1-docker.pkg.dev
  
        - name: Build and Push Backend Docker image
          run: |
            docker build -t northamerica-northeast1-docker.pkg.dev/nifty-catfish-395105/majed-amjad/backend:latest backend/
            docker push northamerica-northeast1-docker.pkg.dev/nifty-catfish-395105/majed-amjad/backend:latest
  
        - name: Deploy Backend Cloud Run
          run: |
            gcloud run deploy backend --image northamerica-northeast1-docker.pkg.dev/nifty-catfish-395105/majed-amjad/backend:latest --platform managed --region us-central1 --allow-unauthenticated --project nifty-catfish-395105
